############# - /api/offers
POST http://localhost:3000/api/offers
content-type: application/json

{
  "title": "Fast Boat",
  "category": "rent",
  "mobile": "Fast Boat",
  "description": "Fast Boat",
  "location": "Hong Kong",
  "price": 4300
}

### 
GET http://localhost:3000/api/offers
content-type: application/json

#####
GET http://localhost:3000/api/offers/paginate?offset=itrF0B0aGTnOrmWcU/recW1ZHcmVQHCjTLN
content-type: application/json


############# - /api/users
POST http://localhost:3000/api/users
content-type: application/json

{
  "email": "konojack@gmail.com",
  "fullName": "Dawid Kon",
  "password": "sdsdfgg"
}
